### ISSUE TITLE
Crafters not displaying redstone control button

### ISSUE THREAD

**Issue by Thogro15** [Edivad99/ExtraStorage#29] opened 2021-05-28 19:39 UTC
**Describe the bug**
When placing crafter there is not button for redstone control, when playing on a multiplayer server. Normal crafter from RS works. Button shows up when playing on a singleplayer world. 

**Configuration**
Mod version: 1.3.1
Forge version: 36.1.2
Minecraft version: 1.16.5
Refined Storage version: 1.9.12
Are you playing on server?: Yes

**To Reproduce**
1. Place any tier of crafter
2. Right click said crafter
3. See that there is no button for redstone control

**Expected behavior**
Place crafter and be able to switch between redstone modes.

**Screenshots**
How its supposed to be:
![image](https://user-images.githubusercontent.com/32090694/120034293-272fb080-bffd-11eb-9e0c-9c2e39bec99a.png)

The bug:
![image](https://user-images.githubusercontent.com/32090694/120034326-3282dc00-bffd-11eb-97b0-58ae7977ca2c.png)

**Additional context**
Button dissapears when playing on server, is there when playing on a singleplayer server. (Modpack is ATM6 To The Sky v. 1.0.9 if relevant)

**Comment by Edivad99** [comment] 2021-05-29 09:51
This issues is a duplicate of #21, on server the mod work, you need to tell me what is the mod that cause the conflict

**Comment by Thogro15** [comment] 2021-05-29 10:06
So i did some testing and it seems to be the mod "cabletiers" https://www.curseforge.com/minecraft/mc-mods/cable-tiers

**Comment by Thogro15** [comment] 2021-05-29 10:25
I also found out that if the Creative Crafter mod is installed the button shows up, but your are not able to change what mode is enabled. https://www.curseforge.com/minecraft/mc-mods/creative-crafter Both of them seem to be made by the same person.

**Comment by Edivad99** [comment] 2021-05-29 10:35
They probably get confused, try disabling both

**Comment by Thogro15** [comment] 2021-05-29 10:52
It works fine when both are disabled, but then again its kinda wierd how it only happens on a server.

**Closed** 2021-09-28 12:30 UTC
Labels: duplicate
