### ISSUE TITLE
(Suggestion) Add an upgrade-to-next-tier item similar to the upgrade items from ironfurnaces or ironchests.

### ISSUE THREAD

**Issue by iFlaxo** [Edivad99/ExtraStorage#64] opened 2022-12-29 07:47 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the feature

if youre unfamiliar with either of the two mods in the title, basically what im suggesting is adding an item that lets you shift right click an existing crafter thats placed in the world with an upgrade-to-next-tier item, allowing you to upgrade it to the next tier without needing to craft an entire new crafter, so upgrade items for taking the default RS crafter to an iron crafter, then another item for upgrading the iron crafter to a gold crafter, etc. Would also be very nice(if this gets implemented) if the crafters retain their patterns & speed/stack upgrades(where applicable) when upgraded to the next tier

**Comment by Edivad99** [comment] 2022-12-29 09:05
Duplicate of #12

**Closed as completed by Edivad99** 2022-12-29 09:05 UTC
Labels: duplicate
